### ISSUE TITLE
POS-sync [QUESTION/ISSUE] Dependent on Internet connection

### ISSUE THREAD

**Issue by blaggacao** [itpp-labs/pos-addons#531]
Is it possible that some of your POS synching modules (eg. through a client triggered heartbeat) might trigger a Odoo "coffee break waiting circle"?
I've not only seen this in the official Odoo App which is blacks out almost immediately if connection is reported as lost, but also on a regular android chrome browser...

**Comment by yelizariev** [comment]
It can be ``pos_longpolling``'s issue, but I didn't see, that it block the POS screen.

I can imagine, that there is some module that uses backend utility (i.e. one for backend and not for POS) to send request to the server. Need a scenario to reproduce to find the problem.

**Comment by blaggacao** [comment]
OK, I'll engage... (forcibly until this Friday, I guess..) ... and obviously share my results.

**Comment by blaggacao** [comment]
Actually I see 2 RPC calls, each without a timeout in pos-multi-session and in pos-longpolling.

pos-longpolling has a timeout construct which I do not understand given the Ajax timeout for json and the Odoo implementation for jsonp.

**Comment by yelizariev** [comment]
Originally we didn't redefine request ``/longpolling/poll`` and use built-in one. Built-in implementation doesn't report in case of any failures and just repeat the request. While we do redefine the request now, I am not sure that can change something there.

How it works now (@GabbasovDinar , @KolushovAlexandr  correct me if I am wrong):

* There are [two timeout values](https://github.com/it-projects-llc/pos-addons/blob/11.0/pos_longpolling/models/pos_longpolling_models.py)
* What we need is to be sure, that longpolling system works. 
* We that purpose we want to get response from server via longpolling often enough
* With pos-multi-session server sends messages via longpollin quite often
* If there are no message from server more than ``query_timeout`` time, we send request PING to server
* Server replies with PONG
* If we haven't got PONG during ``response_timeout`` then we make a conclusion that longpolling doesn't work

Why Ajax timeout is not the same:
* we send request via ajax, but timeout waits response from longpolling

Thoughts?

**Comment by blaggacao** [comment]
Replicate the problem locally:

- Set a js breakpoint here: https://github.com/odoo/odoo/blob/11.0/addons/web/static/src/js/core/session.js#L347
- Set `self.origin_server = false` (we need to make shure that the URL is reconstructed to a invalid one based on `self.prefix` simulating an unresponsive server / network)
- Set `self.prefix = 'http://google.com'`
- Open a new (restaurant) order
- Manually continue on all and every breakpoint hit

Result: UI is kept blocked.

Reason: on client side ajax calls no timeout handle is passed to the window manager. As the UI blocks after 3 seconds exactly, a sensible timeout could be 1 or 2 seconds...

**Comment by blaggacao** [comment]
Example: ~~https://github.com/odoo/odoo/blob/11.0/addons/point_of_sale/static/src/js/models.js#L597-L600~~ https://github.com/odoo/odoo/blob/10.0/addons/point_of_sale/static/src/js/devices.js#L214

Not sure what shadow's for, though... Sounds interesting

**Comment by blaggacao** [comment]
I'm almost there and will share shortly, however, I found that the network status does not recover on it's own once the connection problem is solved as `start_offline_sync_timer` hammers on the connection every 5 seconds while `request_sync_all` does not recover network status, even on success...

Not sure if this is the right way to do it, but I understand that the connection principal is the longpolling channel, however, additionally after the first error, this PING-PONG seems to become unresponsive...

**Comment by blaggacao** [comment]
It's strange, the PING recovers, whereas the PONG does not get through, not sure if it's not issued any more...

**Comment by blaggacao** [comment]
... ON page reload, those PONG seem to get discharged against the web client...

**Comment by blaggacao** [comment]
... it seems that the js call to `/longpolling/poll`, which would trigger a server dispach died...

**Comment by blaggacao** [comment]
...actually the last observation coincides with the previous problems...
the call to `/longpolling/poll` has no timeout, so the defferred just waits forever and never resumes the polling which is why our main means of transport is stuck in the mountains and why the pos periodically will pop up disconnected state, although in the case of the restaurant, the resync all would update the state (I already did the modification to the code suggested by https://github.com/it-projects-llc/pos-addons/issues/531#issuecomment-351807978) and show all green again...

**Comment by blaggacao** [comment]
I mean this deferred rpc call:
```javascript
        var data = {channels: self.channels, last: self.last, options: options};
        session.rpc('/longpolling/poll', data, {shadow : true}).then(function(result) {  // Stuck here forever, never calls `then` again after an error...
            self.on_notification(result);
            if(!self.stop){
                self.poll();
            }
```

**Comment by blaggacao** [comment]
I think doing this is safe:
```javascript
session.rpc('/longpolling/poll', data, {shadow : true},{timeout:60000}).then(function(result)
```
actually it's (one single dict)
```javascript
{shadow : true, timeout:60000}
```
as the server timeout (in other words maximum time to return a poll request is 50 secs), if the server is effectively down, then the polling will gracefully recover.

Note that `self.last` is changed on `self.on_notification()`, in other words on sucess of the deferred rpc call. This means that we do not even risk to miss any bus messages. The only thing that's set is the last chat presence check and we will see one cylce omitting here... or in other words, max 30 seconds, wich we will not miss anyways as our 60 seconds is bigger...

**Comment by blaggacao** [comment]
Yeay! All works now. So I'll share the patch for illustration...
https://gist.github.com/blaggacao/d52f852a8bda27885604770193852406

**Comment by yelizariev** [comment]
Adding timeout seems to be reasonable. I'd only prefer to have a bit bigger time for timeout -- server or browser may be overloaded. Say, +30 sec for longpolling timeout (i.e. 80 sec total) and 30 sec for /update requests.

Can you provide steps to reproduce via network failures emulations? So, we can try behavior depending on timeout values

**Comment by blaggacao** [comment]
The problem is after 3 seconds the UI blocks.. not sure if shadow:true is able to remedy, but I think graceful recovery is an equally attractive option...

**Comment by blaggacao** [comment]
If shadow:true remedies, I think some 5 seconds would be ok, but I'd rather prefer to notify network connectivity problems instantaniously than presenting the user with unexpected behaviour and a lagged problem reporting...

**Comment by blaggacao** [comment]
Restaurants can be troubled places at times... 😄

**Comment by blaggacao** [comment]
For a reliable (large scale) POS Restaurant solution, I think I've seen that for the Kitchen Printer there is no success feedback and that sent orders are just sent as if we where in UDP protocol...
I'll have a look at this, too, today...

**Comment by blaggacao** [comment]
I correct on my last statement:
There is a queue:
```javascript
        function send_printing_job(){
            if(self.receipt_queue.length > 0){
                var r = self.receipt_queue.shift();
                self.connection.rpc('/hw_proxy/print_xml_receipt',{receipt: r},{timeout: 5000})
                    .then(function(){
                        send_printing_job();
                    },function(){
                        self.receipt_queue.unshift(r);
                    });
            }
        }
```

However, the handover might take place, the raspberry accepts, and then power cycles on it's own...
If receipts are not persisted on the raspberry (which I'll readily look up), then it's bad...

The bad thing is not that once in a while an order get's lost and a end consumer angry. That would happen anyway on a power cycle. The bad thing is that the client (restaurant) will not understand the very technical details and a lost order is lost trust and confidence.

**Comment by blaggacao** [comment]
For network emulation, not sure. Should we give pumba https://github.com/gaia-adm/pumba or https://github.com/worstcase/blockade a try?
UPDATE both require iproute2 in the tested containers

**Comment by blaggacao** [comment]
This has been solved yuchee in upstream and in here

**Comment by farazbdm** [comment]
how was this issue closed, i am still facing this, can you please refer to the PR

**Comment by blaggacao** [comment]
@farazda1 Wasn't [this](https://github.com/it-projects-llc/pos-addons/issues/531#issuecomment-351861987) helpful to you?
Else you might look at the reminiscence of it here: https://github.com/odoo/odoo/blob/e8803e91e22ace82f2ff8712e5c81c8c68ad3930/addons/bus/static/src/js/longpolling_bus.js#L186-L187 Unfortunately the history is lost after refactoring, there.

But that evolves around what resolved the problem back then for me.
